use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, bail, Context, Result};
use serde::{Deserialize, Serialize};

#[cfg(test)]
use std::sync::{Mutex, OnceLock};

const GENERATED_PREFIX: &str = "Generated by Skill Reader profile";

#[cfg(test)]
pub(crate) fn skill_reader_test_lock() -> &'static Mutex<()> {
    static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    LOCK.get_or_init(|| Mutex::new(()))
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ProfileAsset {
    pub kind: AssetKind,
    pub id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ProfileTarget {
    pub mode: String,
}

impl Default for ProfileTarget {
    fn default() -> Self {
        Self {
            mode: "project".to_string(),
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Profile {
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub assets: Vec<ProfileAsset>,
    #[serde(default)]
    pub targets: BTreeMap<String, ProfileTarget>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AppliedProfileManifest {
    pub profile_name: String,
    pub tool: ProfileTool,
    #[serde(default)]
    pub generated_paths: Vec<String>,
    #[serde(default)]
    pub managed_files: Vec<String>,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum AssetKind {
    Skill,
    Rule,
    Agents,
}

impl AssetKind {
    pub fn as_str(self) -> &'static str {
        match self {
            AssetKind::Skill => "skill",
            AssetKind::Rule => "rule",
            AssetKind::Agents => "agents",
        }
    }
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum ProfileTool {
    Codex,
    Claude,
    Cursor,
    Windsurf,
    Opencode,
}

impl ProfileTool {
    pub fn all() -> &'static [ProfileTool] {
        &[
            ProfileTool::Codex,
            ProfileTool::Claude,
            ProfileTool::Cursor,
            ProfileTool::Windsurf,
            ProfileTool::Opencode,
        ]
    }

    pub fn as_str(self) -> &'static str {
        match self {
            ProfileTool::Codex => "codex",
            ProfileTool::Claude => "claude",
            ProfileTool::Cursor => "cursor",
            ProfileTool::Windsurf => "windsurf",
            ProfileTool::Opencode => "opencode",
        }
    }
}

#[derive(Clone, Debug)]
struct ResolvedAsset {
    asset: ProfileAsset,
    source_path: PathBuf,
    title: String,
    description: String,
    body: String,
}

pub fn list_profiles() -> Result<Vec<Profile>> {
    ensure_storage_dirs()?;
    let mut profiles = Vec::new();
    for entry in fs::read_dir(profiles_root())? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let yaml_path = path.join("profile.yaml");
        if yaml_path.exists() {
            profiles.push(load_profile(
                path.file_name()
                    .and_then(|name| name.to_str())
                    .ok_or_else(|| anyhow!("Invalid profile directory name"))?,
            )?);
        }
    }
    profiles.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(profiles)
}

pub fn load_profile(name: &str) -> Result<Profile> {
    let yaml_path = profile_yaml(name);
    let text =
        fs::read_to_string(&yaml_path).with_context(|| format!("Profile not found: {}", name))?;
    let mut profile: Profile = serde_yaml::from_str(&text)
        .with_context(|| format!("Failed to parse {}", yaml_path.display()))?;
    if profile.name.is_empty() {
        profile.name = name.to_string();
    }
    Ok(profile)
}

pub fn create_profile(name: &str, description: &str) -> Result<Profile> {
    let clean = validate_name(name)?;
    let path = profile_yaml(&clean);
    if path.exists() {
        bail!("Profile already exists: {}", clean);
    }
    let targets = ProfileTool::all()
        .iter()
        .map(|tool| (tool.as_str().to_string(), ProfileTarget::default()))
        .collect();
    let profile = Profile {
        name: clean,
        description: description.trim().to_string(),
        assets: Vec::new(),
        targets,
    };
    save_profile(&profile)?;
    Ok(profile)
}

pub fn delete_profile(name: &str) -> Result<()> {
    let dir = profiles_root().join(name);
    if !dir.exists() {
        bail!("Profile not found: {}", name);
    }
    fs::remove_dir_all(dir)?;
    Ok(())
}

pub fn add_asset_to_profile(name: &str, kind: AssetKind, asset_id: &str) -> Result<Profile> {
    let mut profile = load_profile(name)?;
    let asset = ProfileAsset {
        kind,
        id: asset_id.trim().to_string(),
    };
    if asset.id.is_empty() {
        bail!("Asset id cannot be empty.");
    }
    resolve_asset(&asset)?;
    if !profile.assets.iter().any(|existing| existing == &asset) {
        profile.assets.push(asset);
        save_profile(&profile)?;
    }
    Ok(profile)
}

pub fn remove_asset_from_profile(name: &str, kind: AssetKind, asset_id: &str) -> Result<Profile> {
    let mut profile = load_profile(name)?;
    profile
        .assets
        .retain(|asset| !(asset.kind == kind && asset.id == asset_id));
    save_profile(&profile)?;
    Ok(profile)
}

pub fn apply_profile(
    name: &str,
    tools: &[ProfileTool],
    cwd: &Path,
) -> Result<Vec<AppliedProfileManifest>> {
    if !cwd.exists() {
        bail!("Project directory not found: {}", cwd.display());
    }
    let profile = load_profile(name)?;
    if profile.assets.is_empty() {
        bail!("Profile '{}' has no assets.", name);
    }
    let resolved_assets = profile
        .assets
        .iter()
        .map(resolve_asset)
        .collect::<Result<Vec<_>>>()?;
    let chosen_tools = if tools.is_empty() {
        profile_tools(&profile)
    } else {
        tools.to_vec()
    };

    let mut manifests = Vec::new();
    for tool in chosen_tools {
        let old_manifest = load_manifest(cwd, name, tool)?;
        if let Some(old) = old_manifest {
            cleanup_previous_application(&old)?;
        }
        let mut manifest = AppliedProfileManifest {
            profile_name: name.to_string(),
            tool,
            generated_paths: Vec::new(),
            managed_files: Vec::new(),
        };
        materialize_profile(cwd, &profile, tool, &resolved_assets, &mut manifest)?;
        save_manifest(cwd, &manifest)?;
        manifests.push(manifest);
    }
    Ok(manifests)
}

fn materialize_profile(
    cwd: &Path,
    profile: &Profile,
    tool: ProfileTool,
    assets: &[ResolvedAsset],
    manifest: &mut AppliedProfileManifest,
) -> Result<()> {
    match tool {
        ProfileTool::Codex => {
            write_skill_assets(&cwd.join(".agents/skills"), profile, tool, assets, manifest)?;
            upsert_instruction_block(&cwd.join("AGENTS.md"), profile, tool, assets, manifest)?;
        }
        ProfileTool::Claude => {
            write_skill_assets(&cwd.join(".claude/skills"), profile, tool, assets, manifest)?;
            upsert_instruction_block(&cwd.join("CLAUDE.md"), profile, tool, assets, manifest)?;
        }
        ProfileTool::Cursor => {
            write_cursor_rule(&cwd.join(".cursor/rules"), profile, tool, assets, manifest)?;
        }
        ProfileTool::Windsurf => {
            write_skill_assets(
                &cwd.join(".windsurf/skills"),
                profile,
                tool,
                assets,
                manifest,
            )?;
            write_windsurf_rule(
                &cwd.join(".windsurf/rules"),
                profile,
                tool,
                assets,
                manifest,
            )?;
        }
        ProfileTool::Opencode => {
            write_skill_assets(
                &cwd.join(".opencode/skills"),
                profile,
                tool,
                assets,
                manifest,
            )?;
            upsert_instruction_block(&cwd.join("AGENTS.md"), profile, tool, assets, manifest)?;
        }
    }
    Ok(())
}

fn write_skill_assets(
    base_dir: &Path,
    profile: &Profile,
    tool: ProfileTool,
    assets: &[ResolvedAsset],
    manifest: &mut AppliedProfileManifest,
) -> Result<()> {
    fs::create_dir_all(base_dir)?;
    for asset in assets
        .iter()
        .filter(|asset| asset.asset.kind == AssetKind::Skill)
    {
        let dest_dir = base_dir.join(&asset.asset.id);
        if dest_dir.exists() {
            fs::remove_dir_all(&dest_dir)?;
        }
        copy_dir_all(&asset.source_path, &dest_dir)?;
        let skill_md = dest_dir.join("SKILL.md");
        if skill_md.exists() {
            let original = fs::read_to_string(&skill_md)?;
            fs::write(
                &skill_md,
                format!("{}\n\n{}", generated_comment(&profile.name, tool), original),
            )?;
        }
        manifest
            .generated_paths
            .push(dest_dir.display().to_string());
    }
    Ok(())
}

fn write_cursor_rule(
    rules_dir: &Path,
    profile: &Profile,
    tool: ProfileTool,
    assets: &[ResolvedAsset],
    manifest: &mut AppliedProfileManifest,
) -> Result<()> {
    fs::create_dir_all(rules_dir)?;
    let path = rules_dir.join(format!("profile-{}.mdc", profile.name));
    let body = render_profile_sections(profile, assets, true);
    let text = format!(
        "---\ndescription: Materialized profile {}\nalwaysApply: true\n---\n\n{}\n\n{}\n",
        profile.name,
        generated_comment(&profile.name, tool),
        body
    );
    fs::write(&path, text)?;
    manifest.generated_paths.push(path.display().to_string());
    Ok(())
}

fn write_windsurf_rule(
    rules_dir: &Path,
    profile: &Profile,
    tool: ProfileTool,
    assets: &[ResolvedAsset],
    manifest: &mut AppliedProfileManifest,
) -> Result<()> {
    fs::create_dir_all(rules_dir)?;
    let path = rules_dir.join(format!("profile-{}.md", profile.name));
    let body = render_profile_sections(profile, assets, false);
    let text = format!(
        "---\ntrigger: always_on\n---\n\n{}\n\n{}\n",
        generated_comment(&profile.name, tool),
        body
    );
    fs::write(&path, text)?;
    manifest.generated_paths.push(path.display().to_string());
    Ok(())
}

fn upsert_instruction_block(
    file_path: &Path,
    profile: &Profile,
    tool: ProfileTool,
    assets: &[ResolvedAsset],
    manifest: &mut AppliedProfileManifest,
) -> Result<()> {
    let body = render_profile_sections(profile, assets, false);
    let block_id = block_id(&profile.name, tool);
    let new_block = format!(
        "{}\n{}\n\n{}\n{}",
        block_start(&block_id),
        generated_comment(&profile.name, tool),
        body,
        block_end(&block_id),
    );
    let existing = fs::read_to_string(file_path).unwrap_or_default();
    let updated = replace_or_append_block(&existing, &block_id, &new_block);
    if let Some(parent) = file_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(file_path, updated)?;
    manifest.managed_files.push(file_path.display().to_string());
    Ok(())
}

fn replace_or_append_block(text: &str, block_id: &str, new_block: &str) -> String {
    let start = block_start(block_id);
    let end = block_end(block_id);
    if let (Some(start_idx), Some(end_idx)) = (text.find(&start), text.find(&end)) {
        let end_idx = end_idx + end.len();
        let mut updated = String::new();
        updated.push_str(&text[..start_idx]);
        updated.push_str(new_block);
        updated.push_str(&text[end_idx..]);
        return format!("{}\n", updated.trim());
    }
    if text.trim().is_empty() {
        return format!("{}\n", new_block.trim());
    }
    format!("{}\n\n{}\n", text.trim_end(), new_block.trim())
}

fn cleanup_previous_application(manifest: &AppliedProfileManifest) -> Result<()> {
    for raw in &manifest.generated_paths {
        let path = PathBuf::from(raw);
        if path.is_dir() {
            let _ = fs::remove_dir_all(&path);
        } else if path.exists() {
            let _ = fs::remove_file(&path);
        }
    }
    for raw in &manifest.managed_files {
        let path = PathBuf::from(raw);
        if !path.exists() {
            continue;
        }
        let text = fs::read_to_string(&path)?;
        let cleaned = remove_block(&text, &block_id(&manifest.profile_name, manifest.tool));
        if cleaned.trim().is_empty() {
            let _ = fs::remove_file(&path);
        } else {
            fs::write(&path, format!("{}\n", cleaned.trim()))?;
        }
    }
    Ok(())
}

fn remove_block(text: &str, block_id: &str) -> String {
    let start = block_start(block_id);
    let end = block_end(block_id);
    if let (Some(start_idx), Some(end_idx)) = (text.find(&start), text.find(&end)) {
        let end_idx = end_idx + end.len();
        let mut updated = String::new();
        updated.push_str(&text[..start_idx]);
        updated.push_str(&text[end_idx..]);
        return updated;
    }
    text.to_string()
}

fn load_manifest(
    cwd: &Path,
    profile_name: &str,
    tool: ProfileTool,
) -> Result<Option<AppliedProfileManifest>> {
    let path = manifest_path(cwd, profile_name, tool);
    if !path.exists() {
        return Ok(None);
    }
    let text = fs::read_to_string(&path)?;
    let manifest = serde_json::from_str(&text)?;
    Ok(Some(manifest))
}

fn save_manifest(cwd: &Path, manifest: &AppliedProfileManifest) -> Result<()> {
    let path = manifest_path(cwd, &manifest.profile_name, manifest.tool);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, serde_json::to_string_pretty(manifest)?)?;
    Ok(())
}

fn manifest_path(cwd: &Path, profile_name: &str, tool: ProfileTool) -> PathBuf {
    cwd.join(".skill-reader")
        .join("applied-profiles")
        .join(format!("{}--{}.json", tool.as_str(), profile_name))
}

fn render_profile_sections(
    profile: &Profile,
    assets: &[ResolvedAsset],
    include_skills: bool,
) -> String {
    let mut sections = Vec::new();
    sections.push(format!("# Profile: {}", profile.name));
    if !profile.description.trim().is_empty() {
        sections.push(profile.description.trim().to_string());
    }
    for asset in assets {
        if asset.asset.kind == AssetKind::Skill && !include_skills {
            continue;
        }
        sections.push(format!(
            "## {}: {}",
            capitalize(asset.asset.kind.as_str()),
            asset.title
        ));
        let body = if asset.asset.kind == AssetKind::Skill && !asset.description.is_empty() {
            format!("{}\n\n{}", asset.description.trim(), asset.body.trim())
        } else {
            asset.body.trim().to_string()
        };
        sections.push(body);
    }
    sections
        .into_iter()
        .filter(|part| !part.trim().is_empty())
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn generated_comment(profile_name: &str, tool: ProfileTool) -> String {
    format!(
        "<!-- {}: {} ({}) -->",
        GENERATED_PREFIX,
        profile_name,
        tool.as_str()
    )
}

fn block_id(profile_name: &str, tool: ProfileTool) -> String {
    format!("profile={};tool={}", profile_name, tool.as_str())
}

fn block_start(block_id: &str) -> String {
    format!("<!-- skill-reader:begin {} -->", block_id)
}

fn block_end(block_id: &str) -> String {
    format!("<!-- skill-reader:end {} -->", block_id)
}

fn profile_tools(profile: &Profile) -> Vec<ProfileTool> {
    if profile.targets.is_empty() {
        return ProfileTool::all().to_vec();
    }
    ProfileTool::all()
        .iter()
        .copied()
        .filter(|tool| profile.targets.contains_key(tool.as_str()))
        .collect()
}

fn save_profile(profile: &Profile) -> Result<()> {
    ensure_storage_dirs()?;
    let dir = profiles_root().join(&profile.name);
    fs::create_dir_all(&dir)?;
    let yaml_path = dir.join("profile.yaml");
    fs::write(&yaml_path, serde_yaml::to_string(profile)?)?;
    Ok(())
}

fn resolve_asset(asset: &ProfileAsset) -> Result<ResolvedAsset> {
    let asset_id = asset.id.trim();
    if asset_id.is_empty() {
        bail!("Asset id cannot be empty.");
    }
    match asset.kind {
        AssetKind::Skill => {
            let source_dir = library_root().join("skills").join(asset_id);
            let skill_md = source_dir.join("SKILL.md");
            let text = fs::read_to_string(&skill_md)
                .with_context(|| format!("Skill asset not found: {}", asset_id))?;
            let (metadata, body) = parse_frontmatter(&text);
            Ok(ResolvedAsset {
                asset: asset.clone(),
                source_path: source_dir,
                title: metadata
                    .get("name")
                    .cloned()
                    .unwrap_or_else(|| asset_id.to_string()),
                description: metadata.get("description").cloned().unwrap_or_default(),
                body: body.trim().to_string(),
            })
        }
        AssetKind::Rule => {
            let rules_root = library_root().join("rules");
            let file = fs::read_dir(&rules_root)?
                .filter_map(|entry| entry.ok())
                .map(|entry| entry.path())
                .find(|path| {
                    path.file_stem()
                        .and_then(|stem| stem.to_str())
                        .map(|stem| stem == asset_id)
                        .unwrap_or(false)
                })
                .ok_or_else(|| anyhow!("Rule asset not found: {}", asset_id))?;
            let text = fs::read_to_string(&file)?;
            let (metadata, body) = parse_frontmatter(&text);
            Ok(ResolvedAsset {
                asset: asset.clone(),
                source_path: file.clone(),
                title: metadata.get("name").cloned().unwrap_or_else(|| {
                    file.file_stem()
                        .and_then(|stem| stem.to_str())
                        .unwrap_or(asset_id)
                        .to_string()
                }),
                description: metadata.get("description").cloned().unwrap_or_default(),
                body: if body.trim().is_empty() {
                    text.trim().to_string()
                } else {
                    body.trim().to_string()
                },
            })
        }
        AssetKind::Agents => {
            let source_file = library_root()
                .join("agents")
                .join(format!("{}.md", asset_id));
            let body = fs::read_to_string(&source_file)
                .with_context(|| format!("Agents asset not found: {}", asset_id))?;
            Ok(ResolvedAsset {
                asset: asset.clone(),
                source_path: source_file,
                title: asset_id.to_string(),
                description: String::new(),
                body: body.trim().to_string(),
            })
        }
    }
}

fn parse_frontmatter(text: &str) -> (BTreeMap<String, String>, String) {
    if let Some(rest) = text.strip_prefix("---\n") {
        if let Some(end_idx) = rest.find("\n---\n") {
            let header = &rest[..end_idx];
            let body = &rest[end_idx + "\n---\n".len()..];
            let metadata = header
                .lines()
                .filter_map(|line| line.split_once(':'))
                .map(|(key, value)| {
                    (
                        key.trim().to_string(),
                        value.trim().trim_matches('"').to_string(),
                    )
                })
                .collect();
            return (metadata, body.to_string());
        }
    }
    (BTreeMap::new(), text.to_string())
}

fn ensure_storage_dirs() -> Result<()> {
    for path in [
        skill_reader_home(),
        profiles_root(),
        library_root().join("skills"),
        library_root().join("rules"),
        library_root().join("agents"),
    ] {
        fs::create_dir_all(path)?;
    }
    Ok(())
}

fn skill_reader_home() -> PathBuf {
    env::var("SKILL_READER_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| expand_home("~/.skill-reader"))
}

fn profiles_root() -> PathBuf {
    skill_reader_home().join("profiles")
}

fn library_root() -> PathBuf {
    skill_reader_home().join("library")
}

fn profile_yaml(name: &str) -> PathBuf {
    profiles_root().join(name).join("profile.yaml")
}

fn validate_name(name: &str) -> Result<String> {
    let clean = name.trim();
    if clean.is_empty() {
        bail!("Name cannot be empty.");
    }
    if !clean
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        bail!("Use only letters, numbers, '-' and '_'.");
    }
    Ok(clean.to_string())
}

fn expand_home(path: &str) -> PathBuf {
    if path == "~/.skill-reader" {
        if let Ok(home) = env::var("HOME") {
            return PathBuf::from(home).join(".skill-reader");
        }
    }
    PathBuf::from(path)
}

fn capitalize(value: &str) -> String {
    let mut chars = value.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

fn copy_dir_all(src: &Path, dst: &Path) -> Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let path = entry.path();
        let dest_path = dst.join(entry.file_name());
        if path.is_dir() {
            copy_dir_all(&path, &dest_path)?;
        } else {
            fs::copy(&path, &dest_path)?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn with_test_home<T>(f: impl FnOnce(&TempDir) -> Result<T>) -> Result<T> {
        let _guard = skill_reader_test_lock().lock().expect("test env lock");
        let temp = TempDir::new()?;
        let previous = env::var_os("SKILL_READER_HOME");
        env::set_var("SKILL_READER_HOME", temp.path().join(".skill-reader"));
        let result = f(&temp);
        if let Some(previous) = previous {
            env::set_var("SKILL_READER_HOME", previous);
        } else {
            env::remove_var("SKILL_READER_HOME");
        }
        result
    }

    fn seed_home(root: &Path) -> Result<()> {
        fs::create_dir_all(root.join(".skill-reader/library/skills/perf-skill"))?;
        fs::write(
            root.join(".skill-reader/library/skills/perf-skill/SKILL.md"),
            "---\nname: perf-skill\ndescription: Improve performance\n---\n\nUse perf guidance.\n",
        )?;
        fs::create_dir_all(root.join(".skill-reader/library/rules"))?;
        fs::write(
            root.join(".skill-reader/library/rules/frontend-guide.md"),
            "---\ndescription: Frontend constraints\n---\n\nAlways test mobile.\n",
        )?;
        fs::create_dir_all(root.join(".skill-reader/library/agents"))?;
        fs::write(
            root.join(".skill-reader/library/agents/team-playbook.md"),
            "# Team playbook\n\nShip carefully.\n",
        )?;
        Ok(())
    }

    #[test]
    fn create_update_and_apply_profile() -> Result<()> {
        with_test_home(|temp| {
            seed_home(temp.path())?;

            create_profile("frontend-audit", "Audit stack")?;
            add_asset_to_profile("frontend-audit", AssetKind::Skill, "perf-skill")?;
            add_asset_to_profile("frontend-audit", AssetKind::Rule, "frontend-guide")?;
            add_asset_to_profile("frontend-audit", AssetKind::Agents, "team-playbook")?;

            let project = temp.path().join("project");
            fs::create_dir_all(&project)?;
            let manifests = apply_profile(
                "frontend-audit",
                &[ProfileTool::Codex, ProfileTool::Cursor],
                &project,
            )?;
            assert_eq!(manifests.len(), 2);
            assert!(project.join(".agents/skills/perf-skill/SKILL.md").exists());
            assert!(project
                .join(".cursor/rules/profile-frontend-audit.mdc")
                .exists());

            let agents = fs::read_to_string(project.join("AGENTS.md"))?;
            assert_eq!(
                agents
                    .matches("skill-reader:begin profile=frontend-audit;tool=codex")
                    .count(),
                1
            );
            Ok(())
        })
    }

    #[test]
    fn list_and_delete_profile() -> Result<()> {
        with_test_home(|temp| {
            seed_home(temp.path())?;
            create_profile("alpha", "A")?;
            create_profile("beta", "B")?;
            let listed = list_profiles()?;
            assert_eq!(listed.len(), 2);
            assert_eq!(listed[0].name, "alpha");
            delete_profile("alpha")?;
            assert!(load_profile("alpha").is_err());
            Ok(())
        })
    }

    #[test]
    fn create_profile_rejects_invalid_names() {
        let err = validate_name("bad name").unwrap_err();
        assert!(err.to_string().contains("Use only letters"));
        let err = validate_name("").unwrap_err();
        assert!(err.to_string().contains("Name cannot be empty"));
    }

    #[test]
    fn add_asset_deduplicates_and_remove_asset_is_safe() -> Result<()> {
        with_test_home(|temp| {
            seed_home(temp.path())?;
            create_profile("alpha", "")?;
            add_asset_to_profile("alpha", AssetKind::Skill, "perf-skill")?;
            add_asset_to_profile("alpha", AssetKind::Skill, "perf-skill")?;
            let profile = load_profile("alpha")?;
            assert_eq!(profile.assets.len(), 1);
            let profile = remove_asset_from_profile("alpha", AssetKind::Rule, "missing")?;
            assert_eq!(profile.assets.len(), 1);
            let profile = remove_asset_from_profile("alpha", AssetKind::Skill, "perf-skill")?;
            assert!(profile.assets.is_empty());
            Ok(())
        })
    }

    #[test]
    fn apply_profile_validates_project_and_assets() -> Result<()> {
        with_test_home(|temp| {
            seed_home(temp.path())?;
            create_profile("empty", "")?;
            let missing_dir = temp.path().join("missing");
            let err = apply_profile("empty", &[ProfileTool::Codex], &missing_dir).unwrap_err();
            assert!(err.to_string().contains("Project directory not found"));

            let project = temp.path().join("project");
            fs::create_dir_all(&project)?;
            let err = apply_profile("empty", &[ProfileTool::Codex], &project).unwrap_err();
            assert!(err.to_string().contains("has no assets"));
            Ok(())
        })
    }

    #[test]
    fn apply_profile_materializes_all_supported_tools() -> Result<()> {
        with_test_home(|temp| {
            seed_home(temp.path())?;
            create_profile("ship", "Ship safely")?;
            add_asset_to_profile("ship", AssetKind::Skill, "perf-skill")?;
            add_asset_to_profile("ship", AssetKind::Rule, "frontend-guide")?;
            add_asset_to_profile("ship", AssetKind::Agents, "team-playbook")?;
            let project = temp.path().join("project");
            fs::create_dir_all(&project)?;

            for tool in ProfileTool::all() {
                apply_profile("ship", &[*tool], &project)?;
            }

            assert!(project.join(".agents/skills/perf-skill/SKILL.md").exists());
            assert!(project.join("AGENTS.md").exists());
            assert!(project.join(".claude/skills/perf-skill/SKILL.md").exists());
            assert!(project.join("CLAUDE.md").exists());
            assert!(project.join(".cursor/rules/profile-ship.mdc").exists());
            assert!(project
                .join(".windsurf/skills/perf-skill/SKILL.md")
                .exists());
            assert!(project.join(".windsurf/rules/profile-ship.md").exists());
            assert!(project
                .join(".opencode/skills/perf-skill/SKILL.md")
                .exists());
            Ok(())
        })
    }

    #[test]
    fn reapply_cleans_previous_generated_files() -> Result<()> {
        with_test_home(|temp| {
            seed_home(temp.path())?;
            create_profile("ship", "Ship safely")?;
            add_asset_to_profile("ship", AssetKind::Skill, "perf-skill")?;
            add_asset_to_profile("ship", AssetKind::Agents, "team-playbook")?;
            let project = temp.path().join("project");
            fs::create_dir_all(&project)?;

            apply_profile("ship", &[ProfileTool::Codex], &project)?;
            let agents_path = project.join("AGENTS.md");
            let first = fs::read_to_string(&agents_path)?;
            assert_eq!(
                first
                    .matches("skill-reader:begin profile=ship;tool=codex")
                    .count(),
                1
            );

            apply_profile("ship", &[ProfileTool::Codex], &project)?;
            let second = fs::read_to_string(&agents_path)?;
            assert_eq!(
                second
                    .matches("skill-reader:begin profile=ship;tool=codex")
                    .count(),
                1
            );
            Ok(())
        })
    }

    #[test]
    fn helper_functions_cover_edge_cases() {
        let (metadata, body) = parse_frontmatter("---\nname: test\ndescription: hi\n---\n\nBody\n");
        assert_eq!(metadata.get("name").unwrap(), "test");
        assert!(body.contains("Body"));

        let (metadata, body) = parse_frontmatter("No frontmatter");
        assert!(metadata.is_empty());
        assert_eq!(body, "No frontmatter");

        let inserted = replace_or_append_block(
            "",
            "profile=x;tool=codex",
            "<!-- skill-reader:begin profile=x;tool=codex -->\nbody\n<!-- skill-reader:end profile=x;tool=codex -->",
        );
        assert!(inserted.contains("body"));

        let replaced = replace_or_append_block(
            &inserted,
            "profile=x;tool=codex",
            "<!-- skill-reader:begin profile=x;tool=codex -->\nnext\n<!-- skill-reader:end profile=x;tool=codex -->",
        );
        assert!(replaced.contains("next"));
        assert!(!replaced.contains("\nbody\n"));

        let removed = remove_block(&replaced, "profile=x;tool=codex");
        assert!(!removed.contains("next"));

        assert_eq!(capitalize("skill"), "Skill");
        assert_eq!(capitalize(""), "");
        assert!(generated_comment("p", ProfileTool::Codex).contains(GENERATED_PREFIX));
        assert_eq!(expand_home("/tmp/x"), PathBuf::from("/tmp/x"));
    }

    #[test]
    fn profile_tools_defaults_and_target_filtering() {
        let empty = Profile {
            name: "x".into(),
            description: String::new(),
            assets: vec![],
            targets: BTreeMap::new(),
        };
        assert_eq!(profile_tools(&empty).len(), ProfileTool::all().len());

        let mut targets = BTreeMap::new();
        targets.insert("codex".to_string(), ProfileTarget::default());
        targets.insert("cursor".to_string(), ProfileTarget::default());
        let filtered = Profile {
            name: "y".into(),
            description: String::new(),
            assets: vec![],
            targets,
        };
        assert_eq!(
            profile_tools(&filtered),
            vec![ProfileTool::Codex, ProfileTool::Cursor]
        );
    }

    #[test]
    fn resolve_asset_errors_for_missing_assets() -> Result<()> {
        with_test_home(|_| {
            ensure_storage_dirs()?;

            let err = resolve_asset(&ProfileAsset {
                kind: AssetKind::Skill,
                id: "missing".into(),
            })
            .unwrap_err();
            assert!(err.to_string().contains("Skill asset not found"));
            let err = resolve_asset(&ProfileAsset {
                kind: AssetKind::Rule,
                id: "missing".into(),
            })
            .unwrap_err();
            assert!(err.to_string().contains("Rule asset not found"));
            let err = resolve_asset(&ProfileAsset {
                kind: AssetKind::Agents,
                id: "missing".into(),
            })
            .unwrap_err();
            assert!(err.to_string().contains("Agents asset not found"));
            Ok(())
        })
    }
}
